# NOTE: I have removed the version number from this file to make it compatible with older versions of docker-compose.
# If you know what you are doing, you can add the version number back in.

# version: "3.9"
services:
  db:
    build: ./db
    container_name: phone-shop-db
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    container_name: phone-shop-backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URL=mongodb://phone-shop-db:27017/phone_shop
      - SESSION_SECRET=dev_secret
      - CORS_ORIGIN=http://localhost:5173,http://localhost:3000
      - SEED_DEMO=true
    depends_on:
      - db
  frontend:
    build: ./frontend
    container_name: phone-shop-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:4000/api
    depends_on:
      - backend
